name: CI

on:
    pull_request: {}
    push:
        branches:
            - main

permissions:
    contents: read

jobs:
    rust:
        name: Rust
        uses: RustForWeb/.github/.github/workflows/rust.yml@94e5af76a27a4691153fae17ed42eb08677f8d3f
        with:
            target: wasm32-unknown-unknown
