name: Website

on:
    pull_request: {}
    push:
        branches:
            - main

permissions:
    contents: read
    id-token: write
    pages: write

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: false

jobs:
    trunk:
        name: Trunk
        uses: RustForWeb/.github/.github/workflows/trunk.yml@94e5af76a27a4691153fae17ed42eb08677f8d3f
